# vim:ft=yaml.ansible
---

# NOTE:
# * .ssh/config needs an entry with `ForwardAgent yes` for the target host,
#   to pull private git repositories from github.
# * this user needs to be in the hosts sudo group and /etc/sudoers needs to
#   be modified to allow no passwd usage of sudo.

- name: Playbook to set up a new system locally
  hosts: all
  gather_facts: true
  vars:
    git_dir: "{{ ansible_env.HOME }}/git"
    nvim_release: "0.10"
  pre_tasks:
    - name: Update apt cache
      tags: always
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
  tasks:
    # Dev
    - name: Core
      ansible.builtin.include_tasks: tasks/core.yml
      tags: core
    - name: Fish
      ansible.builtin.include_tasks: tasks/fish.yml
      tags: fish
    - name: Dotfiles
      ansible.builtin.include_tasks: tasks/dotfiles.yml
      tags: dotfiles
    - name: Nvim
      ansible.builtin.include_tasks: tasks/nvim.yml
      tags: nvim

    # X
    - name: Brave
      ansible.builtin.include_tasks: tasks/brave.yml
      tags: brave
    - name: Telegram
      ansible.builtin.include_tasks: tasks/telegram.yml
      tags: telegram

    # NOTE: needs cargo installed to compile alacritty
    - name: Desktop
      ansible.builtin.include_tasks: tasks/desktop.yml
      tags: X, alacritty

    # TODO:
    # - include: tasks/tor.yml
    # - include: tasks/hacking.yml
    # - include: tasks/mail.yml
    # - include: tasks/nix.yml
    # - include: tasks/docker.yml

    # Old / Unused
    # - include: tasks/ergodox.yml
