# vim:ft=yaml.ansible
---
- name: Install build requirements
  tags: alacritty
  become: true
  block:
    - name: Debian
      ansible.builtin.apt:
        pkg: "{{ cargo_build_requirements_debian }}"
      when: ansible_distribution == 'Debian'

    - name: Fedora
      ansible.builtin.dnf:
        pkg: "{{ cargo_build_requirements_fedora }}"
      when: ansible_distribution == 'Fedora'

- name: Get alacritty
  tags: alacritty
  ansible.builtin.git:
    repo: https://github.com/zenixls2/alacritty.git
    dest: "{{ git_dir }}/alacritty"
    single_branch: true
    version: ligature

- name: Cargo build
  tags: alacritty
  ansible.builtin.command:
    cmd: "{{ cargo }} build --release"
    chdir: "{{ git_dir }}/alacritty"
  changed_when: true

- name: Install
  tags: alacritty
  become: true
  ansible.builtin.copy:
    src: "{{ git_dir }}/alacritty/target/release/alacritty"
    dest: "/usr/local/bin"
    mode: "0755"

- name: Setup alacritty configuration file
  tags: alacritty_config
  ansible.builtin.template:
    src: alacritty.yml.j2
    dest: "{{ ansible_env.HOME }}/.alacritty.yml"
    mode: "0644"
