# vim:ft=yaml.ansible
---
- name: Install build requirements
  tags: alacritty
  become: true
  ansible.builtin.apt:
    pkg:
      - cmake
      - g++
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3

- name: Get alacritty
  tags: alacritty
  ansible.builtin.git:
    repo: https://github.com/zenixls2/alacritty.git
    dest: "{{ git_dir }}/alacritty"
    single_branch: true
    version: ligature

- name: Build
  tags: alacritty
  ansible.builtin.shell: "cd {{ git_dir }}/alacritty && cargo build --release"
  changed_when: true

- name: Install
  tags: alacritty
  become: true
  ansible.builtin.copy:
    src: "{{ git_dir }}/alacritty/target/release/alacritty"
    dest: "/usr/local/bin"
    mode: "0755"

- name: Setup alacritty configuration file
  tags: alacritty, alacritty_config
  ansible.builtin.template:
    src: alacritty.yml.j2
    dest: "{{ ansible_env.HOME }}/.alacritty.yml"
    mode: "0644"
