# vim:ft=ansible
---
- name: Make sure git directory exists
  ansible.builtin.file:
    path: "{{ git_dir }}"
    state: directory
    mode: "0755"
  tags:
    - core
    - dev

- name: Make sure home bin folder exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: "0755"
  tags:
    - core
    - dev

- name: Install core requirements
  become: true
  ansible.builtin.apt:
    pkg:
      - git
      - fzf
      - tmux
      - ripgrep
      - direnv
      - stow
      - gpg
      - btop
  tags:
    - core
    - dev
