# vim:ft=yaml.ansible
---
- name: Create needed directories
  tags: core
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ ansible_env.HOME }}/bin"
    - "{{ ansible_env.HOME }}/dev"
    - "{{ git_dir }}"

- name: Generate locales
  tags: base
  block:
    - name: Copy /etc/locale.gen
      become: true
      ansible.builtin.copy:
        src: locale.gen
        dest: /etc/locale.gen
        mode: "0644"

    - name: Run locale-gen
      become: true
      ansible.builtin.command: locale-gen
      register: out
      changed_when: "'done' in out.stdout"


- name: Install core requirements
  become: true
  ansible.builtin.apt:
    pkg:
      - git
      # - fzf
      # - tmux
      # - ripgrep
      # - direnv
      # - stow
      # - gpg
      # - btop
      # - curl
  tags:
    - core
