# vim:ft=ansible
---
- name: Make sure git directory exists
  file:
    dest: "{{ git_dir }}"
    state: directory
  tags:
    - core

- name: Install core requirements
  become: true
  apt:
    pkg:
      - man-db
      - curl
      - git
      - vim
      - fzf
      - zsh
      - tmux
      - ripgrep
      - htop
      - net-tools
      - ftp
      - nmap
  tags:
    - core
