# vim:ft=ansible
---
- name: Install core requirements
  become: true
  apt:
    pkg:
      - man-db
      - curl
      - git
      - vim
      - fzf
      - zsh
      - tmux
      - ripgrep
      - htop
      - net-tools
  tags:
    - core
