- name: X - Install desktop packages
  become: true
  apt:
    pkg:
      - rxvt-unicode
      - dmenu
      - feh
      - scrot
      - xclip
      - fish
  tags:
    - X

- name: X/fonts - Create fonts directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/"
    state: directory
  tags:
    - fonts
    - X

- name: X/fonts - Install monaco font
  copy:
    src: monaco.ttf
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    force: no
  tags:
    - fonts
    - X

- name: X/fonts - Get/Extract jetbrains
  ansible.builtin.unarchive:
    src: https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip
    dest: "{{ ansible_env.HOME }}/Downloads"
    remote_src: yes
  tags:
    - fonts
    - X

- name: X/fonts - Install jetbrains
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    force: no
  with_fileglob:
    - "{{ ansible_env.HOME }}/Downloads/fonts/ttf/*"
  tags:
    - fonts
    - X

- name: X/fonts - Refresh font cache
  shell: fc-cache
  tags:
    - fonts
    - X

- name: X/Alacritty - Install build requirements
  become: true
  apt:
    pkg:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3
    state: latest
    update_cache: true
    tags:
      - alacritty
      - X


- name: X/Alacritty - Get alacritty
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty.git
    dest: "{{ ansible_env.HOME }}/alacritty"
  tags:
    - alacritty
    - X

- name: X/Alacritty - Cargo build
  shell: "cd {{ ansible_env.HOME }}/alacritty && cargo build --release"
  tags:
    - alacritty
    - X

- name: X/Alacritty - Install
  become: true
  copy:
    src: "{{ ansible_env.HOME }}/alacritty/target/release/alacritty"
    dest: "/usr/local/bin"
    mode: '0755'
  tags:
    - alacritty
    - X
