# vim:ft=ansible
---
- name: X - Install desktop packages
  become: true
  ansible.builtin.apt:
    pkg:
      - rxvt-unicode
      - dmenu
      - feh
      - scrot
      - xclip
  tags:
    - X

- name: X/fonts - Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_env.HOME }}/.local/share/fonts/"
    - "{{ ansible_env.HOME }}/Downloads"
  tags:
    - fonts
    - X

- name: X/fonts - Get/Extract jetbrains
  ansible.builtin.unarchive:
    src: https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip
    dest: "{{ ansible_env.HOME }}/Downloads"
    remote_src: true
  tags:
    - fonts
    - X

- name: X/fonts - Install jetbrains
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    force: false
    mode: "0644"
  with_fileglob:
    - "{{ ansible_env.HOME }}/Downloads/fonts/ttf/*"
  tags:
    - fonts
    - X

- name: X/fonts - Refresh font cache
  ansible.builtin.shell: fc-cache
  tags:
    - fonts
    - X

- name: X/Alacritty - Install build requirements
  become: true
  ansible.builtin.apt:
    pkg:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3
    state: present
    update_cache: true
  tags:
    - alacritty
    - X


- name: X/Alacritty - Get alacritty
  ansible.builtin.git:
    repo: https://github.com/zenixls2/alacritty.git
    dest: "{{ ansible_env.HOME }}/alacritty"
    single_branch: true
    version: ligature
  tags:
    - alacritty
    - X

- name: X/Alacritty - Cargo build
  ansible.builtin.shell: "cd {{ ansible_env.HOME }}/alacritty && cargo build --release"
  tags:
    - alacritty
    - X

- name: X/Alacritty - Install
  become: true
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/alacritty/target/release/alacritty"
    dest: "/usr/local/bin"
    mode: "0755"
  tags:
    - alacritty
    - X
