- name: X - Install desktop packages
  become: true
  apt:
    pkg:
      - rxvt-unicode
      - dmenu
      - feh
      - scrot
      - xclip
  tags:
    - X

- name: X - Create fonts directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/"
    state: directory
  tags:
    - X

- name: X - Install monaco font
  copy:
    src: monaco.ttf
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
  tags:
    - X
