# vim:ft=ansible
---
- name: Clone the .dotfiles repo
  ansible.builtin.git:
    repo: "git@github.com:mxbl/.dotfiles.git"
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    update: true
    accept_hostkey: true
    version: main
  tags:
    - dotfiles
    - dev

# - name: Stow dotfiles (run ~/.dotfiles/install)
#   shell: cd $HOME/.dotfiles && ./install
#   tags:
#     - stow
#     - dotfiles
