# vim:ft=yaml.ansible
---
- name: Fish - Install fish
  tags: fish
  become: true
  ansible.builtin.apt:
    pkg:
      - fish
      - zoxide

- name: Make fish the default shell
  tags: fish
  become: true
  ansible.builtin.user:
    name: mx
    shell: /usr/bin/fish

- name: Setup .config/fish
  tags: fish, fish_config
  ansible.builtin.git:
    repo: "git@github.com:mxbl/fish.git"
    dest: "{{ ansible_env.HOME }}/.config/fish"
    update: true
    accept_hostkey: true
    version: main
