# vim:ft=ansible
---
- name: Install mutt
  become: true
  ansible.builtin.apt:
    pkg:
      - mutt
    state: present
  tags:
    - mail

- name: Create cache directories for mutt
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "755"
  loop:
    - "{{ ansible_env.HOME }}/.mutt/cache/headers"
    - "{{ ansible_env.HOME }}/.mutt/cache/bodies"
  tags:
    - mail

- name: Create certificates store for mutt
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.mutt/certificates"
    state: touch
    mode: "0600"
  tags:
    - mail
