# vim:ft=ansible
---
- name: Install mutt
  apt:
    pkg:
      - mutt
    state: latest
  tags:
    - mail

- name: Create cache directories for mutt
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_env.HOME }}/.mutt/cache/headers"
    - "{{ ansible_env.HOME }}/.mutt/cache/bodies"
  tags:
    - mail

- name: Create certificates store for mutt
  file:
    path: "{{ ansible_env.HOME }}/.mutt/certificates"
    state: touch
  tags:
    - mail
