# vim:ft=yaml.ansible
---

# TODOs:
# - [ ] move s4 git to github
# - [ ] install golang

- name: Cleanup old neovim checkout
  tags: nvim
  ansible.builtin.file:
    path: "{{ git_dir }}/neovim"
    state: absent

- name: Clone neovim
  tags: nvim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ git_dir }}/neovim"
    version: "release-{{ nvim_release }}"

- name: Install build requirements for neovim
  tags: nvim
  become: true
  ansible.builtin.apt:
    pkg:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential
    state: present
    update_cache: true

- name: Build neovim
  tags: nvim
  ansible.builtin.shell: "cd {{ git_dir }}/neovim && make -j 20"
  changed_when: true

- name: Install neovim
  tags: nvim
  become: true
  ansible.builtin.shell: "cd {{ git_dir }}/neovim && make install"
  changed_when: true

- name: Node - Install nodejs and npm
  tags: nvim
  become: true
  ansible.builtin.apt:
    pkg:
      - nodejs
      - npm

- name: Install golang
  tags: nvim, golang
  become: true
  block:
    - name: Cleanup old golang install
      ansible.builtin.file:
        path: /usr/local/go
        state: absent

    - name: Download new golang source
      ansible.builtin.unarchive:
        src: https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz
        dest: /usr/local/
        remote_src: true

- name: Setup .config/nvim
  tags: nvim, nvim_config
  ansible.builtin.git:
    repo: "git@github.com:mxbl/nvim.git"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    update: true
    accept_hostkey: true
    version: main

# - name: Neovim Plugin Development 1
#   become: true
#   apt:
#     pkg:
#       - lua5.2
#       - luarocks
#       - liblua5.2-dev
#   tags:
#     - nvim
#
# - name: Neovim Plugin Development 2 luacheck
#   become: true
#   shell: luarocks install luacheck
#   tags:
#     - nvim

# - name: Clone/Pull lua language server
#   ansible.builtin.git:
#     repo: 'https://github.com/sumneko/lua-language-server'
#     dest: "{{ git_dir }}/lua-language-server"
#     recursive: true
#     update: true
#   tags:
#     - nvim
#     - nvim-lsp

# - name: Build Language Lua Server
#   shell: |
#     cd {{ git_dir }}/lua-language-server/3rd/luamake && ./compile/install.sh
#     cd {{ git_dir }}/lua-language-server && ./3rd/luamake/luamake rebuild
#   tags:
#     - nvim
#     - nvim-lsp

# FIXME: delete! Plug isn't a thing anymore
#
#- name: Make sure Vim-Plug's installation path exists
#  file:
#    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
#    state: directory
#  tags:
#    - nvim
#
#- name: install Vim-Plug
#  get_url:
#    url:  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
#  tags:
#    - nvim
