# vim:ft=ansible
---
- name: Remove neovim
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/neovim"
    state: absent
  tags:
    - nvim

- name: Clone neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ ansible_env.HOME }}/neovim"
    #version: release-0.8
  tags:
    - nvim

- name: Install build requirements for neovim
  become: true
  apt:
    pkg:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: latest
    update_cache: true
  tags:
    - nvim
    - nvim-lsp

- name: Build neovim
  shell: "cd {{ ansible_env.HOME }}/neovim && make -j 20"
  tags:
    - nvim

- name: Install neovim
  become: true
  shell: "cd {{ ansible_env.HOME }}/neovim && make install"
  tags:
    - nvim

- name: Neovim Plugin Development 1
  become: true
  apt:
    pkg:
      - lua5.2
      - luarocks
      - liblua5.2-dev
  tags:
    - nvim

- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - nvim

- name: Clone/Pull lua language server
  ansible.builtin.git:
    repo: 'https://github.com/sumneko/lua-language-server'
    dest: "{{ git_dir }}/lua-language-server"
    recursive: yes
    update:    yes
  tags:
    - nvim
    - nvim-lsp

- name: Build Language Lua Server
  shell: |
    cd {{ git_dir }}/lua-language-server/3rd/luamake && ./compile/install.sh
    cd {{ git_dir }}/lua-language-server && ./3rd/luamake/luamake rebuild
  tags:
    - nvim
    - nvim-lsp

# FIXME: delete! Plug isn't a thing anymore
#
#- name: Make sure Vim-Plug's installation path exists
#  file:
#    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
#    state: directory
#  tags:
#    - nvim
#
#- name: install Vim-Plug
#  get_url:
#    url:  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
#  tags:
#    - nvim
