# vim:ft=ansible
---
- name: Remove neovim
  ansible.builtin.file:
    path: "{{ git_dir }}/neovim"
    state: absent
  tags:
    - nvim
    - dev

- name: Clone neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ git_dir }}/neovim"
    # version: release-0.8
  tags:
    - nvim
    - dev

- name: Install build requirements for neovim
  become: true
  ansible.builtin.apt:
    pkg:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: present
    update_cache: true
  tags:
    - nvim
    - dev

- name: Build neovim
  ansible.builtin.shell: "cd {{ git_dir }}/neovim && make -j 20"
  tags:
    - nvim
    - dev

- name: Install neovim
  become: true
  ansible.builtin.shell: "cd {{ git_dir }}/neovim && make install"
  tags:
    - nvim
    - dev

- name: Node - Install nodejs and npm
  become: true
  ansible.builtin.apt:
    pkg:
      - nodejs
      - npm
  tags:
    - nvim
    - dev

- name: Node - Install N
  become: true
  npm:
    name: n
    global: true
  tags:
    - nvim
    - dev

- name: Node - Install correct version of Node
  become: true
  ansible.builtin.shell: n latest
  tags:
    - nvim
    - dev

- name: Clone the nvim config
  ansible.builtin.git:
    repo: "git@github.com:mxbl/nvim.git"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    update: true
    accept_hostkey: true
    version: main
  tags:
    - nvim
    - dev

# - name: Neovim Plugin Development 1
#   become: true
#   apt:
#     pkg:
#       - lua5.2
#       - luarocks
#       - liblua5.2-dev
#   tags:
#     - nvim
#
# - name: Neovim Plugin Development 2 luacheck
#   become: true
#   shell: luarocks install luacheck
#   tags:
#     - nvim

# - name: Clone/Pull lua language server
#   ansible.builtin.git:
#     repo: 'https://github.com/sumneko/lua-language-server'
#     dest: "{{ git_dir }}/lua-language-server"
#     recursive: true
#     update: true
#   tags:
#     - nvim
#     - nvim-lsp

# - name: Build Language Lua Server
#   shell: |
#     cd {{ git_dir }}/lua-language-server/3rd/luamake && ./compile/install.sh
#     cd {{ git_dir }}/lua-language-server && ./3rd/luamake/luamake rebuild
#   tags:
#     - nvim
#     - nvim-lsp

# FIXME: delete! Plug isn't a thing anymore
#
#- name: Make sure Vim-Plug's installation path exists
#  file:
#    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
#    state: directory
#  tags:
#    - nvim
#
#- name: install Vim-Plug
#  get_url:
#    url:  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
#  tags:
#    - nvim
