- name: telegram - Download desktop app
  get_url:
    url: https://telegram.org/dl/desktop/linux
    dest: /tmp/telegram.archive
  tags:
    - telegram

- name: telegram - Extract archive
  ansible.builtin.unarchive:
    src: /tmp/telegram.archive
    dest: /tmp
  tags:
    - telegram

- name: telegram - copy telegram to system path
  become: true
  copy:
    src:  /tmp/Telegram/Telegram
    dest: /usr/local/bin/telegram
    mode: 0755
  tags:
    - telegram
