# vim:ft=ansible
---
- name: Install zsh
  become: true
  ansible.builtin.apt:
    pkg: zsh
  tags:
    - zsh

- name: Change zsh
  become: true
  ansible.bultin.command: chsh -s $(which zsh) {{ ansible_env.USER }}
  tags:
    - zsh
